shuffle: roundrobin
# Deployment mode: 'local' for local deployment, 'ansible' for remote deployment via Ansible
deployment_mode: local
config:
  activeEpoch: 18
  keyType: "hash-sig"
  # Optional; omit for default 1 (leanSpec src/lean_spec/subspecs/chain/config.py)
  attestation_committee_count: 1
validators:
  - name: "zeam_0"
    privkey: "bdf953adc161873ba026330c56450453f582e3c4ee6cb713644794bcfdd85fe5"
    enrFields:
      # verify /ip4/127.0.0.1/udp/9001/quic-v1/p2p/16Uiu2HAkvi2sxT75Bpq1c7yV2FjnSQJJ432d6jeshbmfdJss1i6f
      ip: "127.0.0.1"
      quic: 9001
    metricsPort: 8081
    apiPort: 5051
    isAggregator: false
    count: 1
  - name: "ream_0"
    privkey: "af27950128b49cda7e7bc9fcb7b0270f7a3945aa7543326f3bfdbd57d2a97a32"
    enrFields:
      #verify /ip4/127.0.0.1/udp/9002/quic-v1/p2p/16Uiu2HAmPQhkD6Zg5Co2ee8ShshkiY4tDePKFARPpCS2oKSLj1E1
      ip: "127.0.0.1"
      quic: 9002
    metricsPort: 8082
    apiPort: 5052
    isAggregator: false
    count: 1
  - name: "zeam_1"
    privkey: "8d14c7b02d55ca050ef97a3961aa16828837fb363e4e19e4dd0060f58670a2b3"
    enrFields:
      ip: "127.0.0.1"
      quic: 9003
    metricsPort: 8083
    apiPort: 5053
    isAggregator: false
    count: 1
  - name: "ethlambda_1"
    privkey: "eb8533a0d5071d4dbcb0c4fcf9b8ac6edc3d1a260d2bb348fafc5cdb455aa1d4"
    enrFields:
      ip: "127.0.0.1"
      quic: 9004
    metricsPort: 8084
    apiPort: 5054
    isAggregator: false
    count: 1

  - name: "lighthouse_0"
    # node id af7df69e602552d2ba639e09ca87107b1bc315306ed434aa86c8515dcad0a252
    # peer id 16Uiu2HAmTrYwvBDY3GLEv5zR48ZfBwCYyKgmuLTDsCdBJUo127HY
    privkey: "4fd22cf461fbeae4947a3fdaef8d533fc7fd1ef1ce4cd98e993210c18234df3f"
    # verify /ip4/127.0.0.1/udp/9005/quic-v1/p2p/16Uiu2HAmTrYwvBDY3GLEv5zR48ZfBwCYyKgmuLTDsCdBJUo127HY
    enrFields:
      ip: "127.0.0.1"
      quic: 9005
    metricsPort: 8085
    apiPort: 5055
    isAggregator: false
    count: 1

  - name: "grandine_0"
    # node id f9e3dfd0eb2e8fb7dfb072b91b23e3286c0fae245cd2c732f4752577f32e5782
    # peer id 16Uiu2HAmErASHzouSQumaetyU18brt4HNUm4151K55ySBQMRLzSS
    privkey: "64a7f5ab53907966374ca23af36392910af682eec82c12e3abbb6c2ccdf39a72"
    # verify /ip4/127.0.0.1/udp/9006/quic-v1/p2p/16Uiu2HAmErASHzouSQumaetyU18brt4HNUm4151K55ySBQMRLzSS
    enrFields:
      ip: "127.0.0.1"
      quic: 9006
    metricsPort: 8086
    apiPort: 8086
    isAggregator: false
    count: 1

  - name: "ethlambda_0"
    # node id 86cec93353ffcc6f38c9c15becadcb30d1acab21a92b30418110c980a38d9c3d
    # peer id 16Uiu2HAmPV5jU62WtmDkCEmfq1jzbBDkGbHNsDN78gJyvmv2TuC5
    privkey: "299550529a79bc2dce003747c52fb0639465c893e00b0440ac66144d625e066a"
    # verify /ip4/127.0.0.1/udp/9007/quic-v1/p2p/16Uiu2HAmPV5jU62WtmDkCEmfq1jzbBDkGbHNsDN78gJyvmv2TuC5
    enrFields:
      ip: "127.0.0.1"
      quic: 9007
    metricsPort: 8087
    apiPort: 8087
    isAggregator: false
    count: 1

  - name: "gean_0"
    privkey: "5e4f4cd02d1c06f715e02ca9939e22ecbca063ad188e080cda4f0786f50367a0"
    enrFields:
      ip: "127.0.0.1"
      quic: 9008
    metricsPort: 8088
    apiPort: 5058
    isAggregator: false
    count: 1

  - name: "peam_0"
    privkey: "8c7b62f4c4a35d134649817f44d2839ad15bcfa1fe6b87991f64d6f54f3ef2a1"
    enrFields:
      ip: "127.0.0.1"
      quic: 9009
    metricsPort: 8089
    apiPort: 5059
    isAggregator: false
    count: 1

  - name: "nlean_0"
    privkey: "2e9be3f1b0d32ca3a4d62017fbfafe3950b7e90fed6802ff8bd2e0f8c4e2ca91"
    enrFields:
      ip: "127.0.0.1"
      quic: 9010
    metricsPort: 8090
    apiPort: 5060
    isAggregator: false
    count: 1
