#!/bin/bash
#
# compute-aggregate-subnet-ids.sh
#
# Print the comma-separated subnet ids that a given aggregator should
# subscribe to.
#
# Why this exists (blockblaz/zeam#863 follow-up):
#   The pre-fix shape exported a CSV of EVERY attestation subnet for
#   every aggregator. With attestation_committee_count=N the libxev
#   thread on each aggregator received N copies of every gossip
#   attestation (one per subscribed topic), and on a 4-subnet devnet-4
#   aggregator that 4× fan-in was a primary contributor to slot-driver
#   starvation (~74% of received attestations referenced unimported
#   heads, each spawned a BlocksByRoot, the storm fed itself).
#
#   The new shape gives each aggregator coverage of its OWN subnet plus
#   exactly ONE neighbor: subnet i listens to {i, (i+1) mod N}. This
#   keeps every subnet covered by at least 2 aggregators (its native
#   one plus the previous subnet's roving neighbor) so aggregation
#   still works, while halving (N=4 → 2 topics) or better the per-
#   aggregator gossip volume.
#
#   For N <= 1 the "neighbor" wraps to the own subnet, so the output
#   degenerates to a single subnet id and the calling client-cmd
#   scripts intentionally drop the `--aggregate-subnet-ids` flag (their
#   guard requires a `,` in the CSV, see e.g. client-cmds/zeam-cmd.sh).
#   For N == 2 every aggregator naturally covers both subnets, which
#   matches the pre-fix behaviour for that case.
#
# Usage:
#   compute-aggregate-subnet-ids.sh <validator-config.yaml> <node-name>
#
# Output:
#   `<own>` when attestation_committee_count <= 1
#   `<own>,<neighbor>` otherwise, where neighbor = (own + 1) mod N
#
# Subnet selection priority for `<own>`:
#   1. Per-row `subnet:` field if present (matches the source of truth
#      that `_node_subnet` in spin-node.sh consults — generated by
#      generate-subnet-config.py / hand-edited devnet layouts).
#   2. Fallback: `validator_index % attestation_committee_count`
#      where validator_index is the cumulative sum of the prior rows'
#      `count` fields (matches how clients themselves choose subnets).
#
# Exits 0 with the CSV on stdout. Errors go to stderr and exit non-zero.

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <validator-config.yaml> <node-name>" >&2
    exit 2
fi

cfg="$1"
node="$2"

if [ ! -f "$cfg" ]; then
    echo "Error: validator config not found: $cfg" >&2
    exit 1
fi

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required (brew install yq / apt install yq)" >&2
    exit 1
fi

# attestation_committee_count, sanitised to a positive integer (default 1).
ac=$(yq eval '.config.attestation_committee_count // 1' "$cfg" | tr -d '\r\n' | head -1)
case "$ac" in ''|*[!0-9]*) ac=1;; esac
if [ "$ac" -lt 1 ] 2>/dev/null; then ac=1; fi

# Own subnet: prefer the explicit `subnet:` field on the validator row.
own=$(yq eval ".validators[] | select(.name == \"$node\") | .subnet // \"\"" "$cfg" | tr -d '\r\n' | head -1)

if [ -z "$own" ]; then
    # Fallback path mirrors `_node_subnet` in spin-node.sh: cumulative
    # `count` sum of the rows preceding this node, modulo `ac`. yq emits
    # rows as `<name> <count>`; we walk them in declaration order.
    vi=0
    while IFS=' ' read -r row_name row_count; do
        if [ "$row_name" = "$node" ]; then
            own=$(( vi % ac ))
            break
        fi
        # Default count to 1 when the row omits the field — matches
        # generate-subnet-config.py's implicit assumption.
        case "$row_count" in ''|null|*[!0-9]*) row_count=1;; esac
        vi=$(( vi + row_count ))
    done < <(yq eval '.validators[] | .name + " " + ((.count // 1) | tostring)' "$cfg")

    if [ -z "$own" ]; then
        echo "Error: node '$node' not found in $cfg" >&2
        exit 1
    fi
fi

# Sanity-bound `own` so a stray YAML value (e.g. subnet: 99 with
# attestation_committee_count: 4) doesn't silently produce a CSV
# referring to non-existent subnets — clients reject those at startup.
if [ "$own" -ge "$ac" ] 2>/dev/null; then
    echo "Error: node '$node' subnet=$own is out of range for attestation_committee_count=$ac" >&2
    exit 1
fi

if [ "$ac" -le 1 ] 2>/dev/null; then
    # Single subnet — nothing to add. Caller will see no `,` in the
    # output and drop --aggregate-subnet-ids accordingly.
    printf '%s\n' "$own"
    exit 0
fi

neighbor=$(( (own + 1) % ac ))
printf '%s,%s\n' "$own" "$neighbor"
